### PR TITLE
st_as_*() and qgis_as_*() methods for qgis_result: change approach to extract element

### LINKED ISSUE #76: st_as_sf() method for qgis_result may miss the OUTPUT element
Interestingly, `st_as_sf()` can be used to process a `qgis_result` object in order to extract the resulting spatial geometry file or layer. Some algorithms provide more than one output. At least in below case the first one is not the primary output, which makes `st_as_sf()` return another layer than the desired one:

``` r
library(qgisprocess)
#> Using 'qgis_process' at '/usr/bin/qgis_process'.
#> QGIS version: 3.22.2-Białowieża
#> Configuration loaded from '~/.cache/R-qgisprocess/cache-0.0.0.9000.rds'
#> Run `qgis_configure()` for details.
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1

curl::curl_download(
  "https://github.com/qgis/QGIS/raw/master/resources/data/world_map.gpkg",
  "world_map.gpkg"
)

result <- 
  qgis_run_algorithm(
    "native:extractbyattribute",
    FIELD = "NAME",
    INPUT = "world_map.gpkg|layername=countries",
    OPERATOR = 0,
    VALUE = "Norway"
  )
#> Using `OUTPUT = qgis_tmp_vector()`
#> Using `FAIL_OUTPUT = qgis_tmp_vector()`
#> Running /usr/bin/qgis_process run 'native:extractbyattribute' \
#>   '--INPUT=world_map.gpkg|layername=countries' '--FIELD=NAME' '--OPERATOR=0' \
#>   '--VALUE=Norway' \
#>   '--OUTPUT=/tmp/RtmpsW8OE7/filee48a47b052c/filee48a630063bb.gpkg' \
#>   '--FAIL_OUTPUT=/tmp/RtmpsW8OE7/filee48a47b052c/filee48a76f8817e.gpkg'
#> qt5ct: using qt5ct plugin
#> 
#> ----------------
#> Inputs
#> ----------------
#> 
#> FAIL_OUTPUT: /tmp/RtmpsW8OE7/filee48a47b052c/filee48a76f8817e.gpkg
#> FIELD:   NAME
#> INPUT:   world_map.gpkg|layername=countries
#> OPERATOR:    0
#> OUTPUT:  /tmp/RtmpsW8OE7/filee48a47b052c/filee48a630063bb.gpkg
#> VALUE:   Norway
#> 
#> 
#> 0...10...20...30...40...50...60...70...80...90...
#> ----------------
#> Results
#> ----------------
#> 
#> FAIL_OUTPUT: /tmp/RtmpsW8OE7/filee48a47b052c/filee48a76f8817e.gpkg
#> OUTPUT:  /tmp/RtmpsW8OE7/filee48a47b052c/filee48a630063bb.gpkg

str(result, 1)
#> List of 6
#>  $ FAIL_OUTPUT     : 'qgis_outputVector' chr "/tmp/RtmpsW8OE7/filee48a47b052c/filee48a76f8817e.gpkg"
#>  $ OUTPUT          : 'qgis_outputVector' chr "/tmp/RtmpsW8OE7/filee48a47b052c/filee48a630063bb.gpkg"
#>  $ .algorithm      : chr "native:extractbyattribute"
#>  $ .args           :List of 6
#>  $ .raw_json_input : NULL
#>  $ .processx_result:List of 4
#>  - attr(*, "class")= chr "qgis_result"

st_as_sf(result)
#> Simple feature collection with 239 features and 6 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -179.9 ymin: -89.9 xmax: 179.9 ymax: 83.6341
#> Geodetic CRS:  WGS 84
#> # A tibble: 239 × 7
#>    iso_a2 NAME     FIPS_10_ ISO_A3 WB_A2 WB_A3                              geom
#>    <chr>  <chr>    <chr>    <chr>  <chr> <chr>                <MULTIPOLYGON [°]>
#>  1 SE     Sweden   SW       SWE    SE    SWE   (((15.70533 56.1164, 15.7269 56.…
#>  2 DE     Germany  GM       DEU    DE    DEU   (((6.798106 53.60444, 6.722423 5…
#>  3 NL     Netherl… NL       NLD    NL    NLD   (((-68.21154 12.22809, -68.19001…
#>  4 RU     Russia   RS       RUS    RU    RUS   (((47.99708 45.46784, 47.99684 4…
#>  5 KH     Cambodia CB       KHM    KH    KHM   (((103.3342 10.58393, 103.3359 1…
#>  6 HR     Croatia  HR       HRV    HR    HRV   (((17.65895 42.74299, 17.74887 4…
#>  7 MM     Myanmar  BM       MMR    MM    MMR   (((98.05747 9.796861, 98.01832 9…
#>  8 VN     Vietnam  VM       VNM    VN    VNM   (((106.6626 8.739814, 106.6392 8…
#>  9 CA     Canada   CA       CAN    CA    CAN   (((-54.65689 49.46572, -54.68545…
#> 10 US     United … US       USA    US    USA   (((-155.9121 19.09619, -155.9199…
#> # … with 229 more rows
(read_sf(result$OUTPUT))
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -9.117421 ymin: -54.45566 xmax: 33.64039 ymax: 80.76948
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   iso_a2 NAME   FIPS_10_ ISO_A3 WB_A2 WB_A3                                 geom
#>   <chr>  <chr>  <chr>    <chr>  <chr> <chr>                   <MULTIPOLYGON [°]>
#> 1 NO     Norway NO       NOR    NO    NOR   (((3.457286 -54.39007, 3.486664 -54…
```

<sup>Created on 2022-01-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Linux Mint 20
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2022-01-14
#>  pandoc   2.14.0.3 @ /usr/lib/rstudio/bin/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date (UTC) lib source
#>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 4.1.0)
#>  class         7.3-19      2021-05-03 [4] CRAN (R 4.1.0)
#>  classInt      0.4-3       2020-04-07 [1] CRAN (R 4.1.0)
#>  cli           3.1.0       2021-10-27 [1] CRAN (R 4.1.2)
#>  crayon        1.4.2       2021-10-29 [1] CRAN (R 4.1.2)
#>  curl          4.3.2       2021-06-23 [1] CRAN (R 4.1.1)
#>  DBI           1.1.1       2021-01-15 [1] CRAN (R 4.1.0)
#>  digest        0.6.29      2021-12-01 [1] CRAN (R 4.1.2)
#>  dplyr         1.0.7       2021-06-18 [1] CRAN (R 4.1.1)
#>  e1071         1.7-9       2021-09-16 [1] CRAN (R 4.1.1)
#>  ellipsis      0.3.2       2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14        2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         0.5.0       2021-05-25 [1] CRAN (R 4.1.0)
#>  fastmap       1.1.0       2021-01-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.2       2021-12-08 [1] CRAN (R 4.1.2)
#>  generics      0.1.1       2021-10-25 [1] CRAN (R 4.1.2)
#>  glue          1.5.1       2021-11-30 [1] CRAN (R 4.1.2)
#>  highr         0.9         2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.2       2021-08-25 [1] CRAN (R 4.1.1)
#>  KernSmooth    2.23-20     2021-05-03 [4] CRAN (R 4.1.0)
#>  knitr         1.36        2021-09-29 [1] CRAN (R 4.1.1)
#>  lifecycle     1.0.1       2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.1       2020-11-17 [1] CRAN (R 4.1.0)
#>  pillar        1.6.4       2021-10-18 [1] CRAN (R 4.1.2)
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.1.0)
#>  processx      3.5.2       2021-04-30 [1] CRAN (R 4.1.0)
#>  proxy         0.4-26      2021-06-07 [1] CRAN (R 4.1.0)
#>  ps            1.6.0       2021-02-28 [1] CRAN (R 4.1.0)
#>  purrr         0.3.4       2020-04-17 [1] CRAN (R 4.1.0)
#>  qgisprocess * 0.0.0.9000  2022-01-14 [1] Github (paleolimbot/qgisprocess@8f421b4)
#>  R6            2.5.1       2021-08-19 [1] CRAN (R 4.1.1)
#>  rappdirs      0.3.3       2021-01-31 [1] CRAN (R 4.1.0)
#>  Rcpp          1.0.7       2021-07-07 [1] CRAN (R 4.1.1)
#>  reprex        2.0.1       2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         0.99.0.9009 2021-11-18 [1] local
#>  rmarkdown     2.11        2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13        2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.2.2       2021-12-06 [1] CRAN (R 4.1.2)
#>  sf          * 1.0-4       2021-11-14 [1] CRAN (R 4.1.2)
#>  stringi       1.7.6       2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr       1.4.0       2019-02-10 [1] CRAN (R 4.1.0)
#>  tibble        3.1.6       2021-11-07 [1] CRAN (R 4.1.2)
#>  tidyselect    1.1.1       2021-04-30 [1] CRAN (R 4.1.0)
#>  units         0.7-2       2021-06-08 [1] CRAN (R 4.1.1)
#>  utf8          1.2.2       2021-07-24 [1] CRAN (R 4.1.1)
#>  vctrs         0.3.8       2021-04-29 [1] CRAN (R 4.1.0)
#>  withr         2.4.3       2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29        2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.1       2020-02-01 [1] CRAN (R 4.1.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

Currently the first usable output is taken by `st_as_sf()` (below). While element names `OUTPUT` or `output` are not always present for all algorithms, it seems to make sense to prefer such element, if present, over the first usable one.

https://github.com/paleolimbot/qgisprocess/blob/75d90b008a2f4d3aff6fd09e22a29f8996b381ce/R/compat-sf.R#L21-L31

I could try to add that with a PR if you like this suggestion.

### LINKED ISSUE #84: Support needed in st_as_sf() for '<dsn>|layername=<name>' output as obtained from qgis_process
If the output file and layer destination are prespecified in 'the QGIS way', i.e. like `ogr:dbname=world.gpkg table=norway` or `ogr:dbname=world.gpkg table=norway (geom)` these are recognized well by the `qgis_process` command. The latter adapts to the way these parameters are seen in the processing tool dialog (from which they can be copied as JSON and fed to `qgis_process` and to `qgis_run_algorithm()` in R).

In its output, `qgis_process` transforms this output specification into a `<dsn>|layername=<name>` syntaxis.

However when passing the same QGIS syntaxis either as a regular `qgis_run_algorithm()` argument [1], or as JSON (typically copied from the QGIS processing tool dialog) [2], `st_as_sf()` fails to read the `<dsn>|layername=<name>` syntaxis of the output element(s).

A reprex for [2] is given in https://github.com/paleolimbot/qgisprocess/pull/74#issuecomment-1014576243.

A reprex for [1] is below:

``` r
library(qgisprocess)
#> Using 'qgis_process' at '/usr/bin/qgis_process'.
#> QGIS version: 3.22.3-Białowieża
#> Configuration loaded from '~/.cache/R-qgisprocess/cache-0.0.0.9000.rds'
#> Run `qgis_configure()` for details.
#> Using JSON for output serialization
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE

curl::curl_download(
  "https://github.com/qgis/QGIS/raw/master/resources/data/world_map.gpkg",
  "world_map.gpkg"
)

qgis_run_algorithm(
    "native:extractbyattribute",
    FIELD = "NAME",
    INPUT = "world_map.gpkg|layername=countries",
    OPERATOR = 0,
    VALUE = "Norway",
    OUTPUT = "ogr:dbname=world.gpkg table=norway",
    FAIL_OUTPUT = "ogr:dbname=world.gpkg table=except_norway"
  ) %>% 
  st_as_sf
#> Running /usr/bin/qgis_process --json run 'native:extractbyattribute' \
#>   '--INPUT=world_map.gpkg|layername=countries' '--FIELD=NAME' '--OPERATOR=0' \
#>   '--VALUE=Norway' '--OUTPUT=ogr:dbname=world.gpkg table=norway' \
#>   '--FAIL_OUTPUT=ogr:dbname=world.gpkg table=except_norway'
#> qt5ct: using qt5ct plugin
#> Error: Cannot open "world.gpkg|layername=except_norway"; The file doesn't seem to exist.
```

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Linux Mint 20
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2022-01-31
#>  pandoc   2.14.0.3 @ /usr/lib/rstudio/bin/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
#>  class         7.3-20     2022-01-13 [4] CRAN (R 4.1.2)
#>  classInt      0.4-3      2020-04-07 [1] CRAN (R 4.1.0)
#>  cli           3.1.0      2021-10-27 [1] CRAN (R 4.1.2)
#>  crayon        1.4.2      2021-10-29 [1] CRAN (R 4.1.2)
#>  curl          4.3.2      2021-06-23 [1] CRAN (R 4.1.1)
#>  DBI           1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
#>  digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
#>  dplyr         1.0.7      2021-06-18 [1] CRAN (R 4.1.1)
#>  e1071         1.7-9      2021-09-16 [1] CRAN (R 4.1.1)
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         1.0.2      2022-01-14 [1] CRAN (R 4.1.2)
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
#>  generics      0.1.1      2021-10-25 [1] CRAN (R 4.1.2)
#>  glue          1.6.0      2021-12-17 [1] CRAN (R 4.1.2)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
#>  jsonlite      1.7.3      2022-01-17 [1] CRAN (R 4.1.2)
#>  KernSmooth    2.23-20    2021-05-03 [4] CRAN (R 4.1.0)
#>  knitr         1.37       2021-12-16 [1] CRAN (R 4.1.2)
#>  lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.0)
#>  pillar        1.6.4      2021-10-18 [1] CRAN (R 4.1.2)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
#>  processx      3.5.2      2021-04-30 [1] CRAN (R 4.1.0)
#>  proxy         0.4-26     2021-06-07 [1] CRAN (R 4.1.0)
#>  ps            1.6.0      2021-02-28 [1] CRAN (R 4.1.0)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
#>  qgisprocess * 0.0.0.9000 2022-01-31 [1] Github (paleolimbot/qgisprocess@3768999)
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
#>  rappdirs      0.3.3      2021-01-31 [1] CRAN (R 4.1.0)
#>  Rcpp          1.0.8      2022-01-13 [1] CRAN (R 4.1.2)
#>  reprex        2.0.1      2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         0.4.12     2021-10-18 [1] CRAN (R 4.1.2)
#>  rmarkdown     2.11       2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
#>  sf          * 1.0-5      2021-12-17 [1] CRAN (R 4.1.2)
#>  stringi       1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
#>  tibble        3.1.6      2021-11-07 [1] CRAN (R 4.1.2)
#>  tidyselect    1.1.1      2021-04-30 [1] CRAN (R 4.1.0)
#>  units         0.7-2      2021-06-08 [1] CRAN (R 4.1.1)
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.1.1)
#>  vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.1.0)
#>  withr         2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29       2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

A suggested remedy will be added in PR #80.

**Note**: passing `"world.gpkg|layername=except_norway"` to `qgis_process` or (in R) `qgis_run_algorithm()` for the _output_ is _not_ a good option. It writes a GPKG named as `world.gpkg|layername=except_norway.gpkg` (which isn't a problem to `st_as_sf()`, then, but it's clearly not what we need).

### PR DESCRIPTION
**Pull request by florisvdh**
Fixes #76, fixes #84.

Regarding `<dsn>|layername=<name>` output (#84), see further down in https://github.com/paleolimbot/qgisprocess/pull/80#issuecomment-1025543409.

``` r
library(qgisprocess)
#> Using 'qgis_process' at '/usr/bin/qgis_process'.
#> QGIS version: 3.22.3-Białowieża
#> Configuration loaded from '~/.cache/R-qgisprocess/cache-0.0.0.9000.rds'
#> Run `qgis_configure()` for details.
#> Using JSON for output serialization
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE

curl::curl_download(
  "https://github.com/qgis/QGIS/raw/master/resources/data/world_map.gpkg",
  "world_map.gpkg"
)

qgis_run_algorithm(
    "native:extractbyattribute",
    FIELD = "NAME",
    INPUT = "world_map.gpkg|layername=countries",
    OPERATOR = 0,
    VALUE = "Norway"
  ) %>% 
  st_as_sf
#> Using `OUTPUT = qgis_tmp_vector()`
#> Using `FAIL_OUTPUT = qgis_tmp_vector()`
#> Running /usr/bin/qgis_process --json run 'native:extractbyattribute' \
#>   '--INPUT=world_map.gpkg|layername=countries' '--FIELD=NAME' '--OPERATOR=0' \
#>   '--VALUE=Norway' \
#>   '--OUTPUT=/tmp/RtmpfayhUA/file7388321d8d87/file73887e0e36c5.gpkg' \
#>   '--FAIL_OUTPUT=/tmp/RtmpfayhUA/file7388321d8d87/file7388654cd7a3.gpkg'
#> qt5ct: using qt5ct plugin
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -9.117421 ymin: -54.45566 xmax: 33.64039 ymax: 80.76948
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   iso_a2 NAME   FIPS_10_ ISO_A3 WB_A2 WB_A3                                 geom
#>   <chr>  <chr>  <chr>    <chr>  <chr> <chr>                   <MULTIPOLYGON [°]>
#> 1 NO     Norway NO       NOR    NO    NOR   (((3.457286 -54.39007, 3.486664 -54…
```

<sup>Created on 2022-01-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Linux Mint 20
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2022-01-26
#>  pandoc   2.14.0.3 @ /usr/lib/rstudio/bin/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
#>  class         7.3-20     2022-01-13 [4] CRAN (R 4.1.2)
#>  classInt      0.4-3      2020-04-07 [1] CRAN (R 4.1.0)
#>  cli           3.1.0      2021-10-27 [1] CRAN (R 4.1.2)
#>  crayon        1.4.2      2021-10-29 [1] CRAN (R 4.1.2)
#>  curl          4.3.2      2021-06-23 [1] CRAN (R 4.1.1)
#>  DBI           1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
#>  digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
#>  dplyr         1.0.7      2021-06-18 [1] CRAN (R 4.1.1)
#>  e1071         1.7-9      2021-09-16 [1] CRAN (R 4.1.1)
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         1.0.2      2022-01-14 [1] CRAN (R 4.1.2)
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
#>  generics      0.1.1      2021-10-25 [1] CRAN (R 4.1.2)
#>  glue          1.6.0      2021-12-17 [1] CRAN (R 4.1.2)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
#>  jsonlite      1.7.3      2022-01-17 [1] CRAN (R 4.1.2)
#>  KernSmooth    2.23-20    2021-05-03 [4] CRAN (R 4.1.0)
#>  knitr         1.37       2021-12-16 [1] CRAN (R 4.1.2)
#>  lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.0)
#>  pillar        1.6.4      2021-10-18 [1] CRAN (R 4.1.2)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
#>  processx      3.5.2      2021-04-30 [1] CRAN (R 4.1.0)
#>  proxy         0.4-26     2021-06-07 [1] CRAN (R 4.1.0)
#>  ps            1.6.0      2021-02-28 [1] CRAN (R 4.1.0)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
#>  qgisprocess * 0.0.0.9000 2022-01-26 [1] local
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
#>  rappdirs      0.3.3      2021-01-31 [1] CRAN (R 4.1.0)
#>  Rcpp          1.0.8      2022-01-13 [1] CRAN (R 4.1.2)
#>  reprex        2.0.1      2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         0.4.12     2021-10-18 [1] CRAN (R 4.1.2)
#>  rmarkdown     2.11       2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
#>  sf          * 1.0-5      2021-12-17 [1] CRAN (R 4.1.2)
#>  stringi       1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
#>  tibble        3.1.6      2021-11-07 [1] CRAN (R 4.1.2)
#>  tidyselect    1.1.1      2021-04-30 [1] CRAN (R 4.1.0)
#>  units         0.7-2      2021-06-08 [1] CRAN (R 4.1.1)
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.1.1)
#>  vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.1.0)
#>  withr         2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29       2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

### CODE REVIEW

**Comment by florisvdh** [comment]
Derived issue #83 from the [failed check on Windows](https://github.com/paleolimbot/qgisprocess/runs/4955664501?check_suite_focus=true#step:11:150). It is caused by the newly added expectation:

https://github.com/paleolimbot/qgisprocess/blob/3d6adb175f813a244d0be3ad498ba7dd3f75e8ed/tests/testthat/test-qgis-result.R#L30-L31

**Comment by florisvdh** [comment]
acaf26f adds support for the `<dsn>|layername=<name>` output syntaxis of `qgis_process` (#84):

``` r
library(qgisprocess)
#> Using 'qgis_process' at '/usr/bin/qgis_process'.
#> QGIS version: 3.22.3-Białowieża
#> Configuration loaded from '~/.cache/R-qgisprocess/cache-0.0.0.9000.rds'
#> Run `qgis_configure()` for details.
#> Using JSON for output serialization
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE

curl::curl_download(
  "https://github.com/qgis/QGIS/raw/master/resources/data/world_map.gpkg",
  "world_map.gpkg"
)

qgis_run_algorithm(
    "native:extractbyattribute",
    FIELD = "NAME",
    INPUT = "world_map.gpkg|layername=countries",
    OPERATOR = 0,
    VALUE = "Norway",
    OUTPUT = "ogr:dbname=world.gpkg table=norway",
    FAIL_OUTPUT = "ogr:dbname=world.gpkg table=except_norway"
  ) %>% 
  st_as_sf
#> Running /usr/bin/qgis_process --json run 'native:extractbyattribute' \
#>   '--INPUT=world_map.gpkg|layername=countries' '--FIELD=NAME' '--OPERATOR=0' \
#>   '--VALUE=Norway' '--OUTPUT=ogr:dbname=world.gpkg table=norway' \
#>   '--FAIL_OUTPUT=ogr:dbname=world.gpkg table=except_norway'
#> qt5ct: using qt5ct plugin
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -9.117421 ymin: -54.45566 xmax: 33.64039 ymax: 80.76948
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   iso_a2 NAME   FIPS_10_ ISO_A3 WB_A2 WB_A3                                 geom
#>   <chr>  <chr>  <chr>    <chr>  <chr> <chr>                   <MULTIPOLYGON [°]>
#> 1 NO     Norway NO       NOR    NO    NOR   (((3.457286 -54.39007, 3.486664 -54…
```

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Linux Mint 20
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2022-01-31
#>  pandoc   2.14.0.3 @ /usr/lib/rstudio/bin/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
#>  class         7.3-20     2022-01-13 [4] CRAN (R 4.1.2)
#>  classInt      0.4-3      2020-04-07 [1] CRAN (R 4.1.0)
#>  cli           3.1.0      2021-10-27 [1] CRAN (R 4.1.2)
#>  crayon        1.4.2      2021-10-29 [1] CRAN (R 4.1.2)
#>  curl          4.3.2      2021-06-23 [1] CRAN (R 4.1.1)
#>  DBI           1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
#>  digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
#>  dplyr         1.0.7      2021-06-18 [1] CRAN (R 4.1.1)
#>  e1071         1.7-9      2021-09-16 [1] CRAN (R 4.1.1)
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         1.0.2      2022-01-14 [1] CRAN (R 4.1.2)
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
#>  generics      0.1.1      2021-10-25 [1] CRAN (R 4.1.2)
#>  glue          1.6.0      2021-12-17 [1] CRAN (R 4.1.2)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
#>  jsonlite      1.7.3      2022-01-17 [1] CRAN (R 4.1.2)
#>  KernSmooth    2.23-20    2021-05-03 [4] CRAN (R 4.1.0)
#>  knitr         1.37       2021-12-16 [1] CRAN (R 4.1.2)
#>  lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.0)
#>  pillar        1.6.4      2021-10-18 [1] CRAN (R 4.1.2)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
#>  processx      3.5.2      2021-04-30 [1] CRAN (R 4.1.0)
#>  proxy         0.4-26     2021-06-07 [1] CRAN (R 4.1.0)
#>  ps            1.6.0      2021-02-28 [1] CRAN (R 4.1.0)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
#>  qgisprocess * 0.0.0.9000 2022-01-31 [1] local
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
#>  rappdirs      0.3.3      2021-01-31 [1] CRAN (R 4.1.0)
#>  Rcpp          1.0.8      2022-01-13 [1] CRAN (R 4.1.2)
#>  reprex        2.0.1      2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         0.4.12     2021-10-18 [1] CRAN (R 4.1.2)
#>  rmarkdown     2.11       2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
#>  sf          * 1.0-5      2021-12-17 [1] CRAN (R 4.1.2)
#>  stringi       1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
#>  tibble        3.1.6      2021-11-07 [1] CRAN (R 4.1.2)
#>  tidyselect    1.1.1      2021-04-30 [1] CRAN (R 4.1.0)
#>  units         0.7-2      2021-06-08 [1] CRAN (R 4.1.1)
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.1.1)
#>  vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.1.0)
#>  withr         2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29       2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

File: tests/testthat/test-qgis-result.R [hunk 1]
```diff
@@ -26,4 +26,7 @@ test_that("qgis_result_*() functions work", {
   expect_true(all(c("URL", "OUTPUT") %in% names(qgis_result_args(result))))
   expect_is(qgis_result_stderr(result), "character")
   expect_is(qgis_result_stdout(result), "character")
+  expect_error(qgis_result_single(result, "numeric"), "zero outputs of type")
+  expect_identical(qgis_result_single(result, "qgis_outputFile"),
+                   result$OUTPUT)
```
Comment (paleolimbot) [inline tests/testthat/test-qgis-result.R:31]: Could you restyle this to match the indentation of long lines in the rest of the package? (See above!)

File: tests/testthat/test-compat-sf.R [hunk 2]
```diff
@@ -19,23 +19,31 @@ test_that("sf objects can be extracted from a qgis_result", {
   skip_if_not_installed("sf")
   skip_if_not(has_qgis())
 
-  result <- qgis_run_algorithm(
+  buffer_longlake <- function(OUTPUT, ...) {
+    qgis_run_algorithm(
```
Comment (paleolimbot) [inline tests/testthat/test-compat-sf.R:23]: Could you fix the indentation here?

**Review by paleolimbot — COMMENTED** [review]
This looks great! I particularly appreciate that you have full test coverage of your changes. I just have a few styling nits (it helps me spot errors if the style is consistent across files in the project).

File: R/qgis-result.R [hunk 3]
```diff
@@ -42,6 +49,27 @@ qgis_error_output_does_not_exist <- function(x, which) {
...
 
+#' @rdname is_qgis_result
+#' @export
+qgis_result_single <- function(x, what) {
+
+  # Limit result to elements that match class
+  x <- x[sapply(x, inherits, what)]
+  if (length(x) == 0L) {
+    abort(paste("Can't extract object from result: zero outputs of type",
+                paste(what, collapse = " or ")))
```
[the remark this answers is not in the document]
Comment (florisvdh) [reply R/qgis-result.R]: Solved in a3f5001.

File: tests/testthat/test-qgis-result.R (hunk 1 above)
Comment (florisvdh) [reply tests/testthat/test-qgis-result.R]: With pleasure. Correct me if I'm wrong; I understand it as follows - i.e. how I applied it in a3f5001:

**Wrong**

```r
  expect_identical(qgis_result_single(result, "qgis_outputFile"),
                   result$OUTPUT)
```

The requirement being: separate lines for arguments and for `)` when, and only when, arguments are splitted over multiple lines.

**Right**

```r
  expect_identical(
    qgis_result_single(result, "qgis_outputFile"),
    result$OUTPUT
    )

```

**Also right (?), but unneeded since this fits in one line**

```r
  expect_identical(
    qgis_result_single(
      result, 
      "qgis_outputFile"
      ),
    result$OUTPUT
    )
```

File: tests/testthat/test-compat-sf.R (hunk 2 above)
Comment (florisvdh) [reply tests/testthat/test-compat-sf.R:23]: Solved in a3f5001.

**Comment by florisvdh** [comment]
I plan to look at the Windows trouble a bit later, including https://github.com/paleolimbot/qgisprocess/issues/83#issuecomment-1027477991 (need to reboot PC to get at that, for local testing - normally I live in Linux).

**Comment by florisvdh** [comment]
Since I found no solution for `native:filedownloader`, I eventually settled on `native:extractbyattribute` since it is a good algorithm to test `qgis_result_single()`. An alternative, `native:reprojectlayer`, is included in 386a11a and also worked (but it's less challenging for `qgis_result_single()`).
