### PR TITLE
qgis_arguments(): support character type element

### LINKED ISSUE #85: Arguments for some functions cannot be obtained with JSON output
This code fails:
```
library(qgisprocess)
options(qgisprocess.use_json_output = TRUE)
qgis_configure()
# just to take a look that it is TRUE
qgis_use_json_output()
qgis_arguments("qgis:executesql")
```

The problem is in these lines: 
https://github.com/paleolimbot/qgisprocess/blob/4a795400af9e4a8b916ee7cda748f5f7fc043af7/R/qgis-help.R#L37
https://github.com/paleolimbot/qgisprocess/blob/4a795400af9e4a8b916ee7cda748f5f7fc043af7/R/qgis-help.R#L40

As these requested values are lists of length 0. I understand the issue but cannot quite figure out simple way to fix it.

There are 37 algorithms with the same issue. I came across it yesterday when automatic build of (**qgis**)[https://github.com/JanCaha/r_package_qgis] failed. The solution is simple, manually set the `options(qgisprocess.use_json_output = FALSE)`, but the problem needs to be adressed.

### PR DESCRIPTION
**Pull request by florisvdh**
For some algorithms, the `type` element in each parameter of `qgis_help(algorithm)$parameters` is a string instead of a list with an `id` element, and could probably serve as `id` directly. This causes issue #85 when running `qgis_arguments()`, i.e. when `qgisprocess.use_json_output = TRUE`.

This PR tries to fix #85 by taking those cases into account; an internal function is added to extract elements from the `type` element, and is used instead of applying `[[`.

A test has been added to include the result for `qgis:executesql`.

Current result (`INPUT_QUERY` is the parameter where it went wrong):

```r
> qgis_arguments("qgis:executesql")
# A tibble: 7 × 6
  name                 description        qgis_type default_value available_values acceptable_valu…
  <chr>                <chr>              <chr>     <list>        <list>           <list>          
1 INPUT_DATASOURCES    Additional input … multilay… <NULL>        <NULL>           <list [0]>      
2 INPUT_QUERY          SQL query          execute_… <NULL>        <NULL>           <NULL>          
3 INPUT_UID_FIELD      Unique identifier… string    <NULL>        <NULL>           <chr [1]>       
4 INPUT_GEOMETRY_FIELD Geometry field     string    <NULL>        <NULL>           <chr [1]>       
5 INPUT_GEOMETRY_TYPE  Geometry type      enum      <NULL>        <chr [8]>        <chr [2]>       
6 INPUT_GEOMETRY_CRS   CRS                crs       <NULL>        <NULL>           <chr [4]>       
7 OUTPUT               SQL Output         sink      <NULL>        <NULL>           <chr [1]>             
```

I didn't actually check whether this result (with a `NULL` as acceptable value!) poses a problem for `qgis_run_algorithm("qgis:executesql")`.

### CODE REVIEW

File: tests/testthat/test-qgis-help.R [hunk 1]
```diff
@@ -31,6 +31,27 @@ test_that("qgis_description() works for algorithms", {
   }
 })
 
+test_that("qgis_arguments() and qgis_outputs() work for selected algorithms", {
+  skip_if_not(has_qgis())
+
+  selected_algorithms <- c("native:buffer", "qgis:executesql")
+
+  for (algorithm in selected_algorithms) {
+    if (interactive()) message(algorithm)
```
Comment (paleolimbot) [inline tests/testthat/test-qgis-help.R:40]: Could you remove this line? I see why it helped when writing the test (I do this all the time), but it's more likely to add confusion than help in the future (in this case, the `algorithm` variable in the global environment will also tell you which algorithm failed).

**Review by paleolimbot — COMMENTED** [review]
Thank you for this! I think it's fine not to test `qgis:executesql`...we'd have to set up a database in the CI and I think it would be rare (an R user could just a database backend).

File: tests/testthat/test-qgis-help.R (hunk 1 above)
Comment (florisvdh) [reply tests/testthat/test-qgis-help.R]: Done in 23a99a1

**Comment by florisvdh** [comment]
What I meant is that I'm not sure whether `qgis_run_algorithms()`, while checking user's input arguments (`qgis_sanitize_arguments()`), will make a problem about any input value for which the 'acceptable value' is `NULL`. Can you judge this? Because this PR introduces such (new) cases. I don't know whether such cases already pre-existed (with acceptable value `NULL`). Apart from `qgis:executesql` @JanCaha mentioned there are a bunch of other algorithms involved too, for now I didn't search which ones.

This appears to relate to using JSON output, which is now default.

**Comment by JanCaha** [comment]
There is couple of them for example `qgis:idwinterpolation`, `qgis:rastercalculator` (this one is know to be problematic), `qgis:relief`, `qgis:tininterpolation`. The others are from saga provider and there is a lot (around 30) of them.
